# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern-cli" do
  version "0.35.4"

  on_macos do
    on_arm do
      sha256 "eefcc873613b35e9ea7993c576e64cba6fb2212cdee6c7cfd7bfceca4cee632a"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3620e4f8b03de96e4e305ba8df52120d332f0f222efb7222374bc3d330252aba"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4698eb29061f02dec05793d8c6f23803e3314b2ddee173f43bc7f46b8b32eb52"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "629c15a68d68b2ad150e0a2de6fe2fc6d03daae38cb879f6e8dd52c717066537"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "lantern-cli"
  desc "Lantern CLI — REPL and scriptable client for a Lantern server"
  homepage "https://github.com/anaregdesign/lantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lantern-cli"]
    end
  end

  # No zap stanza required
end
