# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "705012585f9f8e6b7c9dcf93addc5480eab911778f071fe8a6387f6cc565d22a"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e8839f35d55d9f297e48084218e0067cdb8e167e0832600c7412bf351e903692"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa9293ebc2e95588b3b3569e27b8f8db3f63fcd7ab688d41af7188763d817ced"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c9cd0a6e5742d7eacb3b2f0ea3bbffea9dcd0220bab03a40ffdbe1916384b395"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lantern"
  desc "Lantern — in-memory graph key-vertex-store server (Connect/HTTP-2)"
  homepage "https://github.com/anaregdesign/lantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lantern"]
    end
  end

  # No zap stanza required

end
