# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern-cli" do
  version "0.23.0"

  on_macos do
    on_intel do
      sha256 "7fe38423ee2d9780ec5a85f9b522bf544f010c2adea183cc60cf2c086a553a57"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2343a5e694f7f0d631b1734f6a95d23a824866c87ab627bd3727bc6cc5f9300d"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "febc37eca647980072122ae51d12001a5b6327421659e489b5b11ff883c88d3a"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8068d65d11e132359f46f1b29463406315f9339a7d819d8757d77a3d8fa45400"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lantern-cli"
  desc "Lantern CLI — REPL and scriptable client for a Lantern server"
  homepage "https://github.com/anaregdesign/lantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lantern-cli"]
    end
  end

  # No zap stanza required

end
