# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "f1d1106c955d260d024699efc014e72876b6ff88e8d145c9268f402745282ece"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9d4c31774fef80b650acbdd2b3ad4c2892492f6cfa3c4da4b52e2cbc3ae323b7"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "45f162c25f10d369ffebbb457ad62049a0e92fad0cdc8b80dbcaabb0d297ed9f"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b2ffea4a35336647cf248ab4fc02d7cd9dbdc06d49fb18fbf93340d96aa7b980"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lantern"
  desc "Lantern — in-memory graph key-vertex-store server (Connect/HTTP-2)"
  homepage "https://github.com/anaregdesign/lantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lantern"]
    end
  end

  # No zap stanza required

end
