# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern-cli" do
  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "3780aa5c1d321c21323bcecdba61ff67548a01e1dc24cc943b37f953a5ea83bc"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "81a58875c1e1090528bd6c7ff2d26c777813096c680466a065fa935e86017b65"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f265cbf45c136852ad5835204bde527e09d5cfc490a221ec8a44ef9428fd7d3"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3c10f5f5f240f57a162f25c847ee58a7f6a49c6bd7cf3d129fb66f77d48ce524"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lantern-cli"
  desc "Lantern CLI — REPL and scriptable client for a Lantern server"
  homepage "https://github.com/anaregdesign/lantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lantern-cli"]
    end
  end

  # No zap stanza required

end
