# This file was generated by GoReleaser. DO NOT EDIT.
cask "lantern" do
  version "0.32.1"

  on_macos do
    on_intel do
      sha256 "68d42903b12c1e0515057384246c7071dc9171baf01b52fb935a9e8d4b40a96d"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "26227c7b60d6d5f6825f49f715684d46632751ec892e5d1b5f6c28c3ce2e47e1"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58ba1742da68c0080ee596f538cd1f9cfd20a29cee1bbf16d31700ce23a7cfc1"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8091ca88e4706c0f5002263a693fca96cbe447cc8a7a7eac24cd052e4f3ff670"
      url "https://github.com/anaregdesign/lantern/releases/download/v#{version}/lantern_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "lantern"
  desc "Lantern — in-memory graph key-vertex-store server (Connect/HTTP-2)"
  homepage "https://github.com/anaregdesign/lantern"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lantern"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lantern"]
    end
  end

  # No zap stanza required

end
